// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/types";
import type * as prismicClient from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Blog Post Title
   * - **API ID Path**: blog-post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog-post.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Featured Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog-post.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Excerpt field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Short description of the blog post
   * - **API ID Path**: blog-post.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  excerpt: prismic.KeyTextField;

  /**
   * Author field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Author name
   * - **API ID Path**: blog-post.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author: prismic.KeyTextField;

  /**
   * Publish Date field in *Blog Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog-post.publish_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  publish_date: prismic.DateField /**
   * SEO Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Blog Post Title - Tilbudsskabelon.dk
   * - **API ID Path**: blog-post.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * SEO Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Blog post description for search engines
   * - **API ID Path**: blog-post.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * SEO Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog-post.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog-post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BlogPostDocumentData>,
    "blog-post",
    Lang
  >;

/**
 * Item in *Global Settings → Navigation Menu Items*
 */
export interface GlobalSettingsDocumentDataMenuItemsItem {
  /**
   * Menu Label field in *Global Settings → Navigation Menu Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Home
   * - **API ID Path**: global_settings.menu_items[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Menu Link field in *Global Settings → Navigation Menu Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: /
   * - **API ID Path**: global_settings.menu_items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Global Settings → Quick Links*
 */
export interface GlobalSettingsDocumentDataQuickLinksItem {
  /**
   * Link Label field in *Global Settings → Quick Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Hjem
   * - **API ID Path**: global_settings.quick_links[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link URL field in *Global Settings → Quick Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: /
   * - **API ID Path**: global_settings.quick_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Global Settings documents
 */
interface GlobalSettingsDocumentData {
  /**
   * Header Logo field in *Global Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: global_settings.logo
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Navigation Menu Items field in *Global Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: global_settings.menu_items[]
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  menu_items: prismic.GroupField<
    Simplify<GlobalSettingsDocumentDataMenuItemsItem>
  > /**
   * About Section Title field in *Global Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Om tilbudsskabelon.dk
   * - **API ID Path**: global_settings.about_title
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  about_title: prismic.KeyTextField;

  /**
   * About Description field in *Global Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Tilbudsskabelon.dk er en platform, der gør det nemt for virksomheder at lave skræddersyede og professionelle tilbud.
   * - **API ID Path**: global_settings.about_description
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  about_description: prismic.RichTextField;

  /**
   * Quick Links Section Title field in *Global Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Hurtige links
   * - **API ID Path**: global_settings.quick_links_title
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  quick_links_title: prismic.KeyTextField;

  /**
   * Quick Links field in *Global Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: global_settings.quick_links[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  quick_links: prismic.GroupField<
    Simplify<GlobalSettingsDocumentDataQuickLinksItem>
  >;

  /**
   * Contact Section Title field in *Global Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Kontakt os
   * - **API ID Path**: global_settings.contact_title
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_title: prismic.KeyTextField;

  /**
   * Contact Email field in *Global Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: support@tilbudsskabelon.dk
   * - **API ID Path**: global_settings.contact_email
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_email: prismic.KeyTextField;

  /**
   * Contact Phone field in *Global Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: +45 12345678
   * - **API ID Path**: global_settings.contact_phone
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_phone: prismic.KeyTextField;

  /**
   * Company Address field in *Global Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Company Street 123, 2100 Copenhagen
   * - **API ID Path**: global_settings.company_address
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company_address: prismic.KeyTextField;

  /**
   * Copyright Text field in *Global Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: © 2024 Tilbudsskabelon.dk. Alle rettigheder forbeholdes.
   * - **API ID Path**: global_settings.copyright_text
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  copyright_text: prismic.KeyTextField /**
   * Site Title field in *Global Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Tilbudsskabelon.dk
   * - **API ID Path**: global_settings.site_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  site_title: prismic.KeyTextField;

  /**
   * Site Description field in *Global Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Professional quote templates for Danish businesses
   * - **API ID Path**: global_settings.site_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_description: prismic.KeyTextField;

  /**
   * Default SEO Title field in *Global Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Tilbudsskabelon.dk - Professional Quote Templates
   * - **API ID Path**: global_settings.default_seo_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  default_seo_title: prismic.KeyTextField;

  /**
   * Default SEO Description field in *Global Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Create professional quotes quickly and easily with our Danish quote template platform.
   * - **API ID Path**: global_settings.default_seo_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  default_seo_description: prismic.KeyTextField;

  /**
   * Default SEO Image field in *Global Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: global_settings.default_seo_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  default_seo_image: prismic.ImageField<never>;

  /**
   * Favicon field in *Global Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: global_settings.favicon
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  favicon: prismic.ImageField<never> /**
   * Facebook Page URL field in *Global Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://facebook.com/tilbudsskabelon
   * - **API ID Path**: global_settings.facebook_url
   * - **Tab**: Social
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  facebook_url: prismic.KeyTextField;

  /**
   * LinkedIn Page URL field in *Global Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://linkedin.com/company/tilbudsskabelon
   * - **API ID Path**: global_settings.linkedin_url
   * - **Tab**: Social
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  linkedin_url: prismic.KeyTextField;

  /**
   * Twitter Profile URL field in *Global Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://twitter.com/tilbudsskabelon
   * - **API ID Path**: global_settings.twitter_url
   * - **Tab**: Social
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  twitter_url: prismic.KeyTextField;

  /**
   * Instagram Profile URL field in *Global Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://instagram.com/tilbudsskabelon
   * - **API ID Path**: global_settings.instagram_url
   * - **Tab**: Social
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  instagram_url: prismic.KeyTextField /**
   * Google Analytics ID field in *Global Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: G-KYEV6WW3GJ
   * - **API ID Path**: global_settings.google_analytics_id
   * - **Tab**: Analytics
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  google_analytics_id: prismic.KeyTextField;

  /**
   * Google Tag Manager ID field in *Global Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: GTM-XXXXXXX
   * - **API ID Path**: global_settings.google_tag_manager_id
   * - **Tab**: Analytics
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  google_tag_manager_id: prismic.KeyTextField;

  /**
   * Facebook Pixel ID field in *Global Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 123456789012345
   * - **API ID Path**: global_settings.facebook_pixel_id
   * - **Tab**: Analytics
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  facebook_pixel_id: prismic.KeyTextField /**
   * Privacy Policy field in *Global Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: global_settings.privacy_policy
   * - **Tab**: Legal
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */;
  privacy_policy: prismic.RichTextField;

  /**
   * Terms of Service field in *Global Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: global_settings.terms_of_service
   * - **Tab**: Legal
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  terms_of_service: prismic.RichTextField;

  /**
   * Cookie Policy field in *Global Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: global_settings.cookie_policy
   * - **Tab**: Legal
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  cookie_policy: prismic.RichTextField;
}

/**
 * Global Settings document from Prismic
 *
 * - **API ID**: `global_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalSettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GlobalSettingsDocumentData>,
    "global_settings",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | HeroSlice
  | UspSlice
  | RichTextSlice
  | CtaSlice
  | ImageSlice
  | QuoteFormSlice
  | GuideListingSlice
  | FaqSlice
  | ContactFormSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Page Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Hjem
   * - **API ID Path**: home.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * SEO Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: GRATIS tilbudsskabelon til håndværkere og freelancere
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * SEO Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Tilbudsskabelon.dk er en brugervenlig platform, der hjælper virksomheder med hurtigt og nemt at generere professionelle tilbud.
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * SEO Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

type PageDocumentDataSlicesSlice =
  | HeroSlice
  | UspSlice
  | RichTextSlice
  | CtaSlice
  | ImageSlice
  | QuoteFormSlice
  | GuideListingSlice
  | FaqSlice
  | ContactFormSlice
  | BlogGridSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Page Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Title
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * SEO Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Title - Tilbudsskabelon.dk
   * - **API ID Path**: page.meta_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * SEO Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page description for search engines
   * - **API ID Path**: page.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * SEO Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never> /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Slices
   * - **Documentation**: https://prismic.io/docs/slices
   */;
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes =
  | BlogPostDocument
  | GlobalSettingsDocument
  | HomeDocument
  | PageDocument;

/**
 * Item in *BlogGrid → Default → Primary → Blog Posts*
 */
export interface BlogGridSliceDefaultPrimaryBlogPostsItem {
  /**
   * Blog Post field in *BlogGrid → Default → Primary → Blog Posts*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_grid.default.primary.blog_posts[].blog_post
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  blog_post: ContentRelationshipFieldWithData<
    [
      {
        id: "blog-post";
        fields: [
          "title",
          "description",
          "meta_image",
          "meta_description",
          "meta_title",
          "author",
          "publish_date",
          "excerpt",
          "featured_image",
        ];
      },
    ]
  >;
}

/**
 * Primary content in *BlogGrid → Default → Primary*
 */
export interface BlogGridSliceDefaultPrimary {
  /**
   * Blog Posts field in *BlogGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_grid.default.primary.blog_posts[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  blog_posts: prismic.GroupField<
    Simplify<BlogGridSliceDefaultPrimaryBlogPostsItem>
  >;
}

/**
 * Default variation for BlogGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default blog grid layout
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogGrid*
 */
type BlogGridSliceVariation = BlogGridSliceDefault;

/**
 * BlogGrid Shared Slice
 *
 * - **API ID**: `blog_grid`
 * - **Description**: Blog Grid slice with repeatable blog posts
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogGridSlice = prismic.SharedSlice<
  "blog_grid",
  BlogGridSliceVariation
>;

/**
 * Default variation for CTA Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CTA*
 */
type CtaSliceVariation = CtaSliceDefault;

/**
 * CTA Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: CTA slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Default variation for FAQ Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *FAQ*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * FAQ Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: FAQ slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Hero Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Main headline
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Hero Subtitle field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Supporting text
   * - **API ID Path**: hero.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * CTA Button Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Get Started
   * - **API ID Path**: hero.default.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField;

  /**
   * CTA Button Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: /lav-tilbud
   * - **API ID Path**: hero.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_link: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero banner with title, subtitle and CTA
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Default variation for QuoteForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QuoteformSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *QuoteForm*
 */
type QuoteformSliceVariation = QuoteformSliceDefault;

/**
 * QuoteForm Shared Slice
 *
 * - **API ID**: `quoteform`
 * - **Description**: QuoteForm slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QuoteformSlice = prismic.SharedSlice<
  "quoteform",
  QuoteformSliceVariation
>;

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichtextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichtextSliceVariation = RichtextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `richtext`
 * - **Description**: RichText slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichtextSlice = prismic.SharedSlice<
  "richtext",
  RichtextSliceVariation
>;

/**
 * Primary content in *USP → Items*
 */
export interface UspSliceDefaultItem {
  /**
   * Icon field in *USP → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Icon class or SVG
   * - **API ID Path**: usp.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon: prismic.KeyTextField;

  /**
   * USP Title field in *USP → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Fast & Efficient
   * - **API ID Path**: usp.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * USP Description field in *USP → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Create quotes in minutes
   * - **API ID Path**: usp.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for USP Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type UspSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<UspSliceDefaultItem>
>;

/**
 * Slice variation for *USP*
 */
type UspSliceVariation = UspSliceDefault;

/**
 * USP Shared Slice
 *
 * - **API ID**: `usp`
 * - **Description**: Unique Selling Points grid
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type UspSlice = prismic.SharedSlice<"usp", UspSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismicClient.ClientConfig,
    ): prismicClient.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismicClient.WriteClientConfig,
    ): prismicClient.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismicClient.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogPostDocument,
      BlogPostDocumentData,
      GlobalSettingsDocument,
      GlobalSettingsDocumentData,
      GlobalSettingsDocumentDataMenuItemsItem,
      GlobalSettingsDocumentDataQuickLinksItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      BlogGridSlice,
      BlogGridSliceDefaultPrimaryBlogPostsItem,
      BlogGridSliceDefaultPrimary,
      BlogGridSliceVariation,
      BlogGridSliceDefault,
      CtaSlice,
      CtaSliceVariation,
      CtaSliceDefault,
      FaqSlice,
      FaqSliceVariation,
      FaqSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageSlice,
      ImageSliceVariation,
      ImageSliceDefault,
      QuoteformSlice,
      QuoteformSliceVariation,
      QuoteformSliceDefault,
      RichtextSlice,
      RichtextSliceVariation,
      RichtextSliceDefault,
      UspSlice,
      UspSliceDefaultItem,
      UspSliceVariation,
      UspSliceDefault,
    };
  }
}
