// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type TestDocumentDataSlicesSlice = FaqSlice | CtaSlice | ContactformSlice;

/**
 * Content for test documents
 */
interface TestDocumentData {
  /**
   * Slice Zone field in *test*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: test.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<TestDocumentDataSlicesSlice> /**
   * awdawdawd field in *test*
   *
   * - **Field Type**: Text
   * - **Placeholder**: wad
   * - **API ID Path**: test.awdawdawd
   * - **Tab**: test2
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  awdawdawd: prismic.KeyTextField;
}

/**
 * test document from Prismic
 *
 * - **API ID**: `test`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<TestDocumentData>, "test", Lang>;

export type AllDocumentTypes = TestDocument;

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactformSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactformSliceVariation = ContactformSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contactform`
 * - **Description**: ContactForm slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactformSlice = prismic.SharedSlice<
  "contactform",
  ContactformSliceVariation
>;

/**
 * Default variation for CTA Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CTA*
 */
type CtaSliceVariation = CtaSliceDefault;

/**
 * CTA Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: CTA slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Default variation for FAQ Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *FAQ*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * FAQ Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: FAQ slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Default variation for Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Gallery*
 */
type GallerySliceVariation = GallerySliceDefault;

/**
 * Gallery Shared Slice
 *
 * - **API ID**: `gallery`
 * - **Description**: Gallery slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GallerySlice = prismic.SharedSlice<
  "gallery",
  GallerySliceVariation
>;

/**
 * Default variation for GuideListing Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GuidelistingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *GuideListing*
 */
type GuidelistingSliceVariation = GuidelistingSliceDefault;

/**
 * GuideListing Shared Slice
 *
 * - **API ID**: `guidelisting`
 * - **Description**: GuideListing slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GuidelistingSlice = prismic.SharedSlice<
  "guidelisting",
  GuidelistingSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Hero Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Main headline
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Hero Subtitle field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Supporting text
   * - **API ID Path**: hero.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * CTA Button Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Get Started
   * - **API ID Path**: hero.default.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField;

  /**
   * CTA Button Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: /lav-tilbud
   * - **API ID Path**: hero.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_link: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero banner with title, subtitle and CTA
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Default variation for Info Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InfoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Info*
 */
type InfoSliceVariation = InfoSliceDefault;

/**
 * Info Shared Slice
 *
 * - **API ID**: `info`
 * - **Description**: Info slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InfoSlice = prismic.SharedSlice<"info", InfoSliceVariation>;

/**
 * Default variation for QuoteForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QuoteformSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *QuoteForm*
 */
type QuoteformSliceVariation = QuoteformSliceDefault;

/**
 * QuoteForm Shared Slice
 *
 * - **API ID**: `quoteform`
 * - **Description**: QuoteForm slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QuoteformSlice = prismic.SharedSlice<
  "quoteform",
  QuoteformSliceVariation
>;

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichtextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichtextSliceVariation = RichtextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `richtext`
 * - **Description**: RichText slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichtextSlice = prismic.SharedSlice<
  "richtext",
  RichtextSliceVariation
>;

/**
 * Default variation for Testimonial Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Testimonial*
 */
type TestimonialSliceVariation = TestimonialSliceDefault;

/**
 * Testimonial Shared Slice
 *
 * - **API ID**: `testimonial`
 * - **Description**: Testimonial slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialSlice = prismic.SharedSlice<
  "testimonial",
  TestimonialSliceVariation
>;

/**
 * Primary content in *USP → Items*
 */
export interface UspSliceDefaultItem {
  /**
   * Icon field in *USP → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Icon class or SVG
   * - **API ID Path**: usp.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon: prismic.KeyTextField;

  /**
   * USP Title field in *USP → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Fast & Efficient
   * - **API ID Path**: usp.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * USP Description field in *USP → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Create quotes in minutes
   * - **API ID Path**: usp.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for USP Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type UspSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<UspSliceDefaultItem>
>;

/**
 * Slice variation for *USP*
 */
type UspSliceVariation = UspSliceDefault;

/**
 * USP Shared Slice
 *
 * - **API ID**: `usp`
 * - **Description**: Unique Selling Points grid
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type UspSlice = prismic.SharedSlice<"usp", UspSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      TestDocument,
      TestDocumentData,
      TestDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContactformSlice,
      ContactformSliceVariation,
      ContactformSliceDefault,
      CtaSlice,
      CtaSliceVariation,
      CtaSliceDefault,
      FaqSlice,
      FaqSliceVariation,
      FaqSliceDefault,
      GallerySlice,
      GallerySliceVariation,
      GallerySliceDefault,
      GuidelistingSlice,
      GuidelistingSliceVariation,
      GuidelistingSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageSlice,
      ImageSliceVariation,
      ImageSliceDefault,
      InfoSlice,
      InfoSliceVariation,
      InfoSliceDefault,
      QuoteformSlice,
      QuoteformSliceVariation,
      QuoteformSliceDefault,
      RichtextSlice,
      RichtextSliceVariation,
      RichtextSliceDefault,
      TestimonialSlice,
      TestimonialSliceVariation,
      TestimonialSliceDefault,
      UspSlice,
      UspSliceDefaultItem,
      UspSliceVariation,
      UspSliceDefault,
    };
  }
}
