// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  blog_grid: defineAsyncComponent(() => import("./BlogGrid/index.vue")),
  cta: defineAsyncComponent(() => import("./CTA/CTA.vue")),
  faq: defineAsyncComponent(() => import("./FAQ/FAQ.vue")),
  hero: defineAsyncComponent(() => import("./HeroSlice/HeroSlice.vue")),
  image: defineAsyncComponent(() => import("./Image/Image.vue")),
  quote_form: defineAsyncComponent(() => import("./QuoteForm/QuoteForm.vue")),
  rich_text: defineAsyncComponent(() => import("./RichText/RichText.vue")),
  usp: defineAsyncComponent(() => import("./USP/USP.vue")),
});
